Portfolio-mobile-skeleton
bigmosi/portfolio-mobile-views pull request #1
Opened 2022-02-16 15:33 UTC by bigmosi

Added html file
added css file

2022-02-16 15:45 UTC, Kingstalux reviewed
Hi @bigmosi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that that does not meet the minimum requirements.
- [ ] Your linters have not been set up correctly and as a result the linter checks are not showing on Github. This is probably due to the fact that you copied the wrong code into the `linters.yml` file. It would be great if you could rectify this and make sure you see the linter checks on Github and they should be passing before you submit for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-16 16:30 UTC, KDlamini commented
@bigmosi,
As the previous reviewer has stated, please set up your [linters](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) correctly so that the checks show on your Pull Request.

- I cannot process your review request until all  [linters](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) check. Kindly copy [this linter](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) yml file and try again.

2022-02-16 18:44 UTC, BenMukebo requested changes
### ***Hi @bigmosi***, 

Good work on making more effort on this project there are still some tasks that aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please consider making all changes as mentioned by the previous reviewer, I strongly recommend you take them into consideration.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 19:55 UTC, bigmosi commented on index.html
> +  <header class="header-title">
Okay let me work on it

2022-02-16 21:56 UTC, micheaol requested changes
Hi @bigmosi , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@micheaol) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-16 21:56 UTC, micheaol commented on index.html
> +          <p class="text">Kinyera Amos</p>
Please wrap your name with an `a` tag because this will act as a link in the future to return to home as requested by the previous code reviewer.

Example:
 `<a class="text">Kinyera Amos</a>`

2022-02-16 21:56 UTC, micheaol commented on index.html
> +          <img src="assets/images/Union.png" alt="" >
As requested by the previous code reviewer. Please wrap your `hamburger` in a `nav` tag.

Example:
`<nav>`
        ` <img src="assets/images/Union.png" alt="" >`
`</nav>`

2022-02-16 21:56 UTC, micheaol commented on index.html
> +        If you like what you see and have a project you need coded,
Please try to follow as much as possible the Figma's design. There is a difference in margins and position of your header elements with the ones in Figma. As requested by the previous code reviewer.

2022-02-16 21:58 UTC, micheaol commented on index.html
> +  <header class="header-title">
Please try to follow as much as possible the Figma's design. There is a difference in margins and position of your header elements with the ones in Figma. As requested by the previous code reviewer.

2022-02-17 06:05 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @bigmosi ,  

Your project is complete! Congratulations!  🎉💯🌟 

## Optional suggestions

_Please check the optional suggestions below_

***
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

***
Cheers and Happy coding! :clap: :clap: :clap:

Code review by **Shoira**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear. 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 08:09 UTC, merged